version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD:Welcome123#
    volumes:
      - C:/oracleDB:/opt/oracle/oradata
      - C:/workspace/oracle-ws/docker-practice/createservice/scripts:/opt/oracle/scripts/setup
    networks:
      - backend
  cs-app:
    #image: app:1.0
    build: .
    ports:
      - "8081:8081"
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - backend
networks:
  backend:
    driver: bridge